name: Web App application Testing Workflow

on:
  pull_request:
    branches: 
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (e.g. production, staging)'
        required: true

jobs:
  test-run--build:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.8'

      - name: Setup all build dependencies
        run: |
          chmod +x update_libraries_ubuntu.sh
          ./update_libraries_ubuntu.sh

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --no-cache

      - name: Run testApp
        run: |
          python3 test_app.py
